/*
 * Server-side <head> tags and crawler content for public URLs.
 *
 * The site renders in the browser, so every URL is served the same HTML shell.
 * This fills that shell in per URL before it leaves the server:
 *   · <title>, description, canonical, Open Graph / Twitter tags, JSON-LD
 *   · for a customer card, a readable summary of the card (cardSummaryHtml)
 * so link previews on WhatsApp / Facebook / X / LinkedIn, and crawlers that do
 * not run JavaScript, get the page's real identity instead of a blank shell.
 *
 * Marketing pages take their title, description, canonical and breadcrumbs
 * from src/lib/publicSeo.ts — the same table the browser uses — so the raw
 * HTML and the page after JavaScript runs can no longer disagree.
 *
 * Pure functions + a cached file read — no framework deps, so it's unit-testable.
 */
import fs from "fs";
import path from "path";
import { seoForPath, canonicalPathFor, breadcrumbJsonLd } from "../../src/lib/publicSeo";
import { cardSeo, type CardSeo } from "../../src/lib/cardSeo";

const SITE = "https://digitalcarda.in";

const esc = (s: unknown) =>
  String(s ?? "").replace(/[&<>"]/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" }[c] || c));

type Row = Record<string, unknown>;

/** A legacy JSON data file (customers, product), re-read at most once a minute. */
const jsonCache = new Map<string, { rows: Row[]; at: number }>();
function legacyRows(distPath: string, file: string): Row[] {
  const now = Date.now();
  const hit = jsonCache.get(file);
  if (hit && now - hit.at < 60_000) return hit.rows;
  for (const p of [path.resolve(distPath, `${file}.json`), path.resolve(`./public/${file}.json`)]) {
    try {
      const rows = JSON.parse(fs.readFileSync(p, "utf-8"));
      if (Array.isArray(rows)) { jsonCache.set(file, { rows, at: now }); return rows; }
    } catch { /* try next */ }
  }
  return hit?.rows ?? [];
}

export interface CardMeta {
  title: string; description: string; image: string; url: string;
  jsonLd?: string; ogType?: string; imageW?: number; imageH?: number; imageType?: string; imageAlt?: string;
  /** BreadcrumbList JSON-LD, written with the id the browser keeps in step on navigation. */
  breadcrumbLd?: string;
  /** Visually hidden <h1> placed in the empty shell, when there is nothing better. */
  h1?: string;
  /** Pre-escaped markup placed in the empty shell instead of the lone h1. */
  bodyHtml?: string;
  locale?: string; keywords?: string;
  /** e.g. "noindex, follow" for a paused or empty card. */
  robots?: string;
}

// Site-wide 1200×630 social banner for the marketing pages (generated by
// scripts/gen-og-default.mjs). Correct OG size so link previews render large.
const OG_IMAGE = `${SITE}/og-default.jpg`;

/* The standard screen-reader-only pattern. Used for content that exists for
   readers who never see the painted page — screen readers, and crawlers that
   read raw HTML — and that React replaces when the real page mounts, so it can
   never flash on screen as unstyled text. */
const SR_ONLY = "position:absolute;width:1px;height:1px;padding:0;margin:-1px;overflow:hidden;clip:rect(0,0,0,0);white-space:normal;border:0";

/** Meta for any public page — marketing routes or a customer card. */
export function metaFor(pathname: string, distPath: string): CardMeta | null {
  const clean = pathname.replace(/\/+$/, "") || "/";
  const mk = seoForPath(clean);
  if (mk) {
    // An alias (e.g. /card-designs) canonicalises to the page it duplicates.
    // The home URL keeps its trailing slash, matching what the browser sets.
    const canon = canonicalPathFor(clean);
    return {
      title: mk.title, description: mk.description,
      image: OG_IMAGE, imageW: 1200, imageH: 630, imageType: "image/jpeg", imageAlt: mk.title,
      url: `${SITE}${canon}`, h1: mk.title, locale: "en_IN",
      breadcrumbLd: breadcrumbJsonLd(clean) ?? undefined,
    };
  }
  return cardMetaFor(pathname, distPath);
}

/** Short content hash → cache-busting token for the OG image URL. */
function ogVersion(parts: unknown[]): string {
  const s = parts.map((p) => String(p ?? "")).join("|");
  let h = 5381;
  for (let i = 0; i < s.length; i++) h = ((h << 5) + h + s.charCodeAt(i)) >>> 0;
  return h.toString(36).slice(0, 6);
}

/** A customer's website as an absolute http(s) URL, or "" when it isn't one.
    Bare domains ("pacewalk.com") are what most customers type. */
function websiteUrl(raw: string): string {
  const v = raw.trim();
  if (/^https?:\/\/[^\s]+\.[^\s]+/i.test(v)) return v;
  if (/^[a-z0-9-]+(\.[a-z0-9-]+)+(\/[^\s]*)?$/i.test(v)) return `https://${v}`;
  return "";
}

/**
 * A crawler-readable summary of a customer card, sent in the raw HTML.
 *
 * Why it's needed: the card renders in the browser, inside a sandboxed srcdoc
 * iframe. A crawler that doesn't run JavaScript got the <title> and nothing
 * else, and even one that does sees an empty page around an iframe.
 *
 * What goes in is limited on purpose to facts the card already shows publicly
 * AND that are harmless as plain HTML: name, role, company, business type and
 * city, the About text when the card shows it, products/services, and the
 * website. The street address is reduced to the city. Phone and email are left out
 * deliberately. They ARE on the card, but a card built in the browser keeps
 * them away from the scraper bots that only read raw HTML, and putting them
 * here would hand every customer's number to those bots.
 *
 * Visually hidden: React replaces #root with the real card on mount.
 */
export function cardSummaryHtml(seo: CardSeo, c: Record<string, unknown>): string {
  const { name, role, company, nature, city, about, services } = seo;
  const site = websiteUrl(String(c.url ?? ""));

  const parts = [`<h1>${esc(name)}</h1>`];
  const line = [role, company && company.toLowerCase() !== name.toLowerCase() ? company : ""].filter(Boolean).join(" at ");
  if (line) parts.push(`<p>${esc(line)}</p>`);
  const where = [nature, city].filter(Boolean).join(" · ");
  if (where) parts.push(`<p>${esc(where)}</p>`);
  if (about) parts.push(`<h2>About ${esc(company || name)}</h2>`, `<p>${esc(about.slice(0, 600))}</p>`);
  if (services.length) {
    parts.push(`<h2>Products &amp; services</h2>`, `<ul>${services.slice(0, 12).map((x) => `<li>${esc(x)}</li>`).join("")}</ul>`);
  }
  if (site) {
    // ugc + nofollow: the link is customer-entered, not an editorial endorsement.
    const label = site.replace(/^https?:\/\//i, "").replace(/\/$/, "");
    parts.push(`<p><a href="${esc(site)}" rel="nofollow ugc noopener">${esc(label)}</a></p>`);
  }
  return `<div style="${SR_ONLY}">${parts.join("")}</div>`;
}

/** Returns OG meta for a card path, or null if the path isn't a known card. */
export function cardMetaFor(pathname: string, distPath: string): CardMeta | null {
  const m = pathname.match(/^\/(?:c\/)?([^/]+)\/?$/);
  if (!m) return null;
  const slug = decodeURIComponent(m[1]).toLowerCase();
  if (!slug || slug.includes(".")) return null; // skip files like favicon.ico
  const row = legacyRows(distPath, "customers").find((x) => String(x.slug || "").toLowerCase() === slug);
  if (!row) return null;

  const logo = String(row.logo || "");
  // Generated per card (name, role, company, logo + a QR of this card's URL)
  // so a shared link previews as that person's card, not a stock photo.
  const image = `${SITE}/og/${encodeURIComponent(slug)}.png?v=${ogVersion([String(row.name || slug).trim(), row.company_name, row.designation, logo])}`;
  // The legacy card shows the products whose `uname` matches its slug
  // (src/lib/cardContent.ts loadCustomerContent) — the same ones are used here.
  const products = legacyRows(distPath, "product").filter((p) => String(p.uname ?? "").toLowerCase() === slug);
  const seo = cardSeo({ slug, customer: row, products, image: logo ? image : undefined });

  return {
    title: seo.title, description: seo.description, image, url: `${SITE}/${slug}`,
    jsonLd: seo.jsonLd, breadcrumbLd: seo.breadcrumbLd, ogType: "profile", h1: seo.name,
    bodyHtml: cardSummaryHtml(seo, row), locale: "en_IN",
    ...(seo.keywords ? { keywords: seo.keywords } : {}),
    ...(seo.indexable ? {} : { robots: "noindex, follow" }),
    imageW: 1200, imageH: 630, imageType: "image/png", imageAlt: `${seo.name}'s digital business card`,
  };
}

/** Inject the meta (+ optional JSON-LD and crawler content) into an index.html string. */
export function injectCardMeta(html: string, meta: CardMeta): string {
  const alt = meta.imageAlt || meta.title;
  const ld = (json: string) => json.replace(/</g, "\\u003c");
  const tags = [
    `<meta name="description" content="${esc(meta.description)}">`,
    ...(meta.robots ? [`<meta name="robots" content="${esc(meta.robots)}">`] : []),
    ...(meta.keywords ? [`<meta name="keywords" content="${esc(meta.keywords)}">`] : []),
    `<link rel="canonical" href="${esc(meta.url)}">`,
    `<meta property="og:type" content="${esc(meta.ogType || "website")}">`,
    `<meta property="og:site_name" content="DigitalCarda">`,
    `<meta property="og:locale" content="${esc(meta.locale || "en_IN")}">`,
    `<meta property="og:title" content="${esc(meta.title)}">`,
    `<meta property="og:description" content="${esc(meta.description)}">`,
    `<meta property="og:url" content="${esc(meta.url)}">`,
    `<meta property="og:image" content="${esc(meta.image)}">`,
    `<meta property="og:image:secure_url" content="${esc(meta.image)}">`,
    `<meta property="og:image:alt" content="${esc(alt)}">`,
    ...(meta.imageW ? [`<meta property="og:image:width" content="${meta.imageW}">`] : []),
    ...(meta.imageH ? [`<meta property="og:image:height" content="${meta.imageH}">`] : []),
    ...(meta.imageType ? [`<meta property="og:image:type" content="${esc(meta.imageType)}">`] : []),
    `<meta name="twitter:card" content="summary_large_image">`,
    `<meta name="twitter:site" content="@DigitalCarda">`,
    `<meta name="twitter:creator" content="@DigitalCarda">`,
    `<meta name="twitter:title" content="${esc(meta.title)}">`,
    `<meta name="twitter:description" content="${esc(meta.description)}">`,
    `<meta name="twitter:image" content="${esc(meta.image)}">`,
    `<meta name="twitter:image:alt" content="${esc(alt)}">`,
    ...(meta.jsonLd ? [`<script type="application/ld+json">${ld(meta.jsonLd)}</script>`] : []),
    // Same id PublicLayout updates on in-app navigation, so there's only ever one.
    ...(meta.breadcrumbLd ? [`<script type="application/ld+json" id="dc-breadcrumb-ld">${ld(meta.breadcrumbLd)}</script>`] : []),
  ].join("\n    ");

  // Every replacement below is a FUNCTION, not a string. Titles and
  // descriptions include customer-written SEO fields, and in a replacement
  // string `$&`, `` $` `` and `$'` are patterns — one in a customer's title
  // would splice the surrounding shell into their page's <head>.
  let out = html
    // The shell carries a site-wide default description for routes nothing
    // matches. Drop it before adding the page's own, or every matched page ships
    // two and search engines pick either.
    .replace(/<meta\s+name="description"[^>]*>\s*/i, () => "")
    .replace(/<title>[\s\S]*?<\/title>/, () => `<title>${esc(meta.title)}</title>`)
    .replace("</head>", () => `    ${tags}\n  </head>`);

  const body = meta.bodyHtml
    ?? (meta.h1 ? `<h1 style="${SR_ONLY}">${esc(meta.h1)}</h1>` : "");
  if (body) out = out.replace(/<div id="root">\s*<\/div>/, () => `<div id="root">${body}</div>`);
  return out;
}
