/*
 * Server-side <head> tags and crawler content for public URLs.
 *
 * The site renders in the browser, so every URL is served the same HTML shell.
 * This fills that shell in per URL before it leaves the server:
 *   · <title>, description, canonical, Open Graph / Twitter tags, JSON-LD
 *   · for a customer card, a readable summary of the card (cardSummaryHtml)
 * so link previews on WhatsApp / Facebook / X / LinkedIn, and crawlers that do
 * not run JavaScript, get the page's real identity instead of a blank shell.
 *
 * Marketing pages take their title and description from src/lib/publicSeo.ts —
 * the same table the browser uses — so the raw HTML and the page after
 * JavaScript runs can no longer disagree.
 *
 * Pure functions + a cached file read — no framework deps, so it's unit-testable.
 */
import fs from "fs";
import path from "path";
import { seoForPath } from "../../src/lib/publicSeo";

const SITE = "https://digitalcarda.in";

const esc = (s: unknown) =>
  String(s ?? "").replace(/[&<>"]/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" }[c] || c));

type Row = { slug?: string; name?: string; designation?: string; company_name?: string; about_us?: string; about_on?: unknown; logo?: string; url?: string };

let cache: Row[] | null = null;
let cacheAt = 0;
function customers(distPath: string): Row[] {
  const now = Date.now();
  if (cache && now - cacheAt < 60_000) return cache;
  for (const p of [path.resolve(distPath, "customers.json"), path.resolve("./public/customers.json")]) {
    try { cache = JSON.parse(fs.readFileSync(p, "utf-8")); cacheAt = now; return cache!; } catch { /* try next */ }
  }
  return cache ?? [];
}

export interface CardMeta {
  title: string; description: string; image: string; url: string;
  jsonLd?: string; ogType?: string; imageW?: number; imageH?: number; imageType?: string; imageAlt?: string;
  /** Visually hidden <h1> placed in the empty shell, when there is nothing better. */
  h1?: string;
  /** Pre-escaped markup placed in the empty shell instead of the lone h1. */
  bodyHtml?: string;
  locale?: string; keywords?: string;
}

// Site-wide 1200×630 social banner for the marketing pages (generated by
// scripts/gen-og-default.mjs). Correct OG size so link previews render large.
const OG_IMAGE = `${SITE}/og-default.jpg`;

/* The standard screen-reader-only pattern. Used for content that exists for
   readers who never see the painted page — screen readers, and crawlers that
   read raw HTML — and that React replaces when the real page mounts, so it can
   never flash on screen as unstyled text. */
const SR_ONLY = "position:absolute;width:1px;height:1px;padding:0;margin:-1px;overflow:hidden;clip:rect(0,0,0,0);white-space:normal;border:0";

/** Meta for any public page — marketing routes or a customer card. */
export function metaFor(pathname: string, distPath: string): CardMeta | null {
  const clean = pathname.replace(/\/+$/, "") || "/";
  const mk = seoForPath(clean);
  if (mk) return { ...mk, image: OG_IMAGE, imageW: 1200, imageH: 630, imageType: "image/jpeg", imageAlt: mk.title, url: `${SITE}${clean === "/" ? "" : clean}`, h1: mk.title, locale: "en_IN" };
  return cardMetaFor(pathname, distPath);
}

/** Short content hash → cache-busting token for the OG image URL. */
function ogVersion(parts: unknown[]): string {
  const s = parts.map((p) => String(p ?? "")).join("|");
  let h = 5381;
  for (let i = 0; i < s.length; i++) h = ((h << 5) + h + s.charCodeAt(i)) >>> 0;
  return h.toString(36).slice(0, 6);
}

/** Legacy rich text (about_us) → one line of plain text. Tags go, the handful of
    entities the old editor produced are decoded, and the result is escaped
    again by the caller — so nothing from the field reaches the page as markup. */
function plainText(html: string): string {
  return html
    .replace(/<[^>]*>/g, " ")
    .replace(/&nbsp;/gi, " ")
    .replace(/&quot;/gi, '"')
    .replace(/&#0?39;|&apos;/gi, "'")
    .replace(/&lt;/gi, "<")
    .replace(/&gt;/gi, ">")
    .replace(/&amp;/gi, "&")
    .replace(/\s+/g, " ")
    .trim();
}

/** A customer's website as an absolute http(s) URL, or "" when it isn't one.
    Bare domains ("pacewalk.com") are what most customers type. */
function websiteUrl(raw: string): string {
  const v = raw.trim();
  if (/^https?:\/\/[^\s]+\.[^\s]+/i.test(v)) return v;
  if (/^[a-z0-9-]+(\.[a-z0-9-]+)+(\/[^\s]*)?$/i.test(v)) return `https://${v}`;
  return "";
}

/**
 * A crawler-readable summary of a customer card, sent in the raw HTML.
 *
 * Why it's needed: the card renders in the browser, inside a sandboxed srcdoc
 * iframe. A crawler that doesn't run JavaScript got the <title> and nothing
 * else, and even one that does sees an empty page around an iframe.
 *
 * What goes in is limited on purpose to facts the card already shows publicly
 * AND that are harmless as plain HTML: name, role, company, the About text when
 * the card shows it, and the website. Phone and email are left out
 * deliberately. They ARE on the card, but a card built in the browser keeps
 * them away from the scraper bots that only read raw HTML, and putting them
 * here would hand every customer's number to those bots.
 *
 * Visually hidden: React replaces #root with the real card on mount.
 */
export function cardSummaryHtml(c: Record<string, unknown>, fallbackName: string): string {
  const s = (v: unknown) => String(v ?? "").trim();
  const name = s(c.name) || fallbackName;
  const role = s(c.designation);
  const company = s(c.company_name);
  // Same rule the card uses (buildCard.ts `on`): a missing toggle means shown.
  const aboutShown = Number(c.about_on ?? 1) === 1;
  const about = aboutShown ? plainText(s(c.about_us)).slice(0, 600) : "";
  const site = websiteUrl(s(c.url));

  const parts = [`<h1>${esc(name)}</h1>`];
  const line = [role, company].filter(Boolean).join(" at ");
  if (line) parts.push(`<p>${esc(line)}</p>`);
  if (about) parts.push(`<h2>About ${esc(company || name)}</h2>`, `<p>${esc(about)}</p>`);
  if (site) {
    // ugc + nofollow: the link is customer-entered, not an editorial endorsement.
    const label = site.replace(/^https?:\/\//i, "").replace(/\/$/, "");
    parts.push(`<p><a href="${esc(site)}" rel="nofollow ugc noopener">${esc(label)}</a></p>`);
  }
  return `<div style="${SR_ONLY}">${parts.join("")}</div>`;
}

/** Returns OG meta for a card path, or null if the path isn't a known card. */
export function cardMetaFor(pathname: string, distPath: string): CardMeta | null {
  const m = pathname.match(/^\/(?:c\/)?([^/]+)\/?$/);
  if (!m) return null;
  const slug = decodeURIComponent(m[1]).toLowerCase();
  if (!slug || slug.includes(".")) return null; // skip files like favicon.ico
  const row = customers(distPath).find((x) => String(x.slug || "").toLowerCase() === slug);
  if (!row) return null;

  const name = String(row.name || slug).trim();
  const title = `${name}${row.company_name ? " · " + row.company_name : ""} — DigitalCarda`;
  const description = (row.designation
    ? `${row.designation}${row.company_name ? " at " + row.company_name : ""}`
    : String(row.about_us || "").replace(/<[^>]*>/g, "").slice(0, 150)) || "View my digital business card.";
  const logo = String(row.logo || "");
  // Generated per card (name, role, company, logo + a QR of this card's URL)
  // so a shared link previews as that person's card, not a stock photo.
  const image = `${SITE}/og/${encodeURIComponent(slug)}.png?v=${ogVersion([name, row.company_name, row.designation, logo])}`;
  const url = `${SITE}/${slug}`;
  // Genuine Person structured data — helps rich results / AI answers (§52).
  const jsonLd = JSON.stringify({
    "@context": "https://schema.org", "@type": "Person", name, url,
    ...(row.designation ? { jobTitle: String(row.designation) } : {}),
    ...(row.company_name ? { worksFor: { "@type": "Organization", name: String(row.company_name) } } : {}),
    ...(logo ? { image } : {}),
  });
  return { title, description, image, url, jsonLd, ogType: "profile", h1: name, bodyHtml: cardSummaryHtml(row, name), locale: "en_IN",
    imageW: 1200, imageH: 630, imageType: "image/png", imageAlt: `${name}'s digital business card` };
}

/** Inject the meta (+ optional JSON-LD and crawler content) into an index.html string. */
export function injectCardMeta(html: string, meta: CardMeta): string {
  const alt = meta.imageAlt || meta.title;
  const tags = [
    `<meta name="description" content="${esc(meta.description)}">`,
    ...(meta.keywords ? [`<meta name="keywords" content="${esc(meta.keywords)}">`] : []),
    `<link rel="canonical" href="${esc(meta.url)}">`,
    `<meta property="og:type" content="${esc(meta.ogType || "website")}">`,
    `<meta property="og:site_name" content="DigitalCarda">`,
    `<meta property="og:locale" content="${esc(meta.locale || "en_IN")}">`,
    `<meta property="og:title" content="${esc(meta.title)}">`,
    `<meta property="og:description" content="${esc(meta.description)}">`,
    `<meta property="og:url" content="${esc(meta.url)}">`,
    `<meta property="og:image" content="${esc(meta.image)}">`,
    `<meta property="og:image:secure_url" content="${esc(meta.image)}">`,
    `<meta property="og:image:alt" content="${esc(alt)}">`,
    ...(meta.imageW ? [`<meta property="og:image:width" content="${meta.imageW}">`] : []),
    ...(meta.imageH ? [`<meta property="og:image:height" content="${meta.imageH}">`] : []),
    ...(meta.imageType ? [`<meta property="og:image:type" content="${esc(meta.imageType)}">`] : []),
    `<meta name="twitter:card" content="summary_large_image">`,
    `<meta name="twitter:site" content="@DigitalCarda">`,
    `<meta name="twitter:creator" content="@DigitalCarda">`,
    `<meta name="twitter:title" content="${esc(meta.title)}">`,
    `<meta name="twitter:description" content="${esc(meta.description)}">`,
    `<meta name="twitter:image" content="${esc(meta.image)}">`,
    `<meta name="twitter:image:alt" content="${esc(alt)}">`,
    ...(meta.jsonLd ? [`<script type="application/ld+json">${meta.jsonLd.replace(/</g, "\\u003c")}</script>`] : []),
  ].join("\n    ");

  // Every replacement below is a FUNCTION, not a string. Titles and
  // descriptions include customer-written SEO fields, and in a replacement
  // string `$&`, `` $` `` and `$'` are patterns — one in a customer's title
  // would splice the surrounding shell into their page's <head>.
  let out = html
    // The shell carries a site-wide default description for routes nothing
    // matches. Drop it before adding the page's own, or every matched page ships
    // two and search engines pick either.
    .replace(/<meta\s+name="description"[^>]*>\s*/i, () => "")
    .replace(/<title>[\s\S]*?<\/title>/, () => `<title>${esc(meta.title)}</title>`)
    .replace("</head>", () => `    ${tags}\n  </head>`);

  const body = meta.bodyHtml
    ?? (meta.h1 ? `<h1 style="${SR_ONLY}">${esc(meta.h1)}</h1>` : "");
  if (body) out = out.replace(/<div id="root">\s*<\/div>/, () => `<div id="root">${body}</div>`);
  return out;
}
